spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: teady
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect:
        #show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 2000
        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace